# These are supported funding model platforms

github: NefaroXX

# Additional platforms can be enabled by uncommenting a line below and
# filling in the account name. See
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# buy_me_a_coffee: <username>
# ko-fi: <username>
# patreon: <username>
