[package]
name = "concerto-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
concerto-core = { path = "../core", version = "0.1.0" }
concerto-api-types = { path = "../api-types", version = "0.1.0" }
concerto-config = { path = "../config", version = "0.1.0" }

tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = "1"
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
time = { workspace = true }

camino = { workspace = true }
blake3 = { workspace = true }
imara-diff = { workspace = true }
gix = { workspace = true }
regex = { workspace = true }
nix = { version = "0.26", default-features = false, features = ["signal"] }

[dev-dependencies]
tempfile = "3"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "virtual_fs"
harness = false
